---
resources:
- name: resource-files
  type: git
  source: 
    uri: https://github.com/ericwayman/concourse_ml_workflow_example.git
    branch: master
- name: resource-gist
  type: git
  source:
    branch: master
    uri: {{gist-url}}
    private_key: {{github-private-key}}

jobs:
- name: job-train_save_results
  serial: true 
  plan:
  - get: resource-files
  - get: resource-gist
  - task: train_save_results
    file: resource-files/03_pipeline_train_keras_model_push_results/push_results.yml
  - put: resource-gist
    params: {repository: updated_gist}